name: Build new docs

on:
  workflow_dispatch:
    inputs:
      doc_system:
        description: Either pdoc, or mkdocs
        default: pdoc
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel
        python -m pip install .
        python -m pip install --upgrade pdoc3
        python -m pip install --upgrade mkdocs
    # if doc_type is mkdocs

    - name: Deploy docs
    uses: mhausenblas/mkdocs-deploy-gh-pages@master
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    if: ${{ github.event.inputs.doc_system }} == "mkdocs"


    # If doc_type is pdoc
    - name: remove source files
      run: rm -rf *
      if: ${{ github.event.inputs.doc_system }} == "pdoc"
    - name: build html files
      run: |
        python -m pdoc ezspreadsheet --html --force
        mv "html/ezspreadsheet.html" "html/index.html"
      if: ${{ github.event.inputs.doc_system }} == "pdoc"
    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html
      if: ${{ github.event.inputs.doc_system }} == "pdoc"